AnimalesRoboticosG/AnimalesRoboticosG/Controllers/ComunasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Conexiones.Animales.Models;

namespace AnimalesRoboticosG.Controllers
{
    public class ComunasController : Controller
    {
        private ComercioRoboticoEntities db = new ComercioRoboticoEntities();

        // GET: Comunas
        public ActionResult Index()
        {
            List<Comunas> listado = db.Comunas.Where(x => x.eliminado == false).ToList();
            return View(listado);
        }

        // GET: Comunas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunas comunas = db.Comunas.Find(id);
            if (comunas == null)
            {
                return HttpNotFound();
            }
            return View(comunas);
        }

        // GET: Comunas/Create
        public ActionResult Create()
        {
            ViewBag.idRegion = new SelectList(db.Regiones, "id", "nombre");
            return View();
        }

        // POST: Comunas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comunas comunas)
        {
            if (ModelState.IsValid)
            {
                db.Comunas.Add(comunas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idRegion = new SelectList(db.Regiones, "id", "nombre", comunas.idRegion);
            return View(comunas);
        }

        // GET: Comunas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunas comunas = db.Comunas.Find(id);
            if (comunas == null)
            {
                return HttpNotFound();
            }
            ViewBag.idRegion = new SelectList(db.Regiones, "id", "nombre", comunas.idRegion);
            return View(comunas);
        }

        // POST: Comunas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comunas comunas)
        {
            if (ModelState.IsValid)
            {
                Comunas comu = db.Comunas.Find(comunas.id);
                comu.nombre = comunas.nombre;
                comu.idRegion = comunas.idRegion;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idRegion = new SelectList(db.Regiones, "id", "nombre", comunas.idRegion);
            return View(comunas);
        }

        // GET: Comunas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunas comunas = db.Comunas.Find(id);
            if (comunas == null)
            {
                return HttpNotFound();
            }
            return View(comunas);
        }

        // POST: Comunas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comunas comunas = db.Comunas.Find(id);
            if (comunas != null) 
            {
                comunas.eliminado = true;
                comunas.fechaEliminacion = DateTime.Now;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalesRoboticosG/AnimalesRoboticosG/Controllers/PaisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Conexiones.Animales.Models;

namespace AnimalesRoboticosG.Controllers
{
    public class PaisesController : Controller
    {
        private ComercioRoboticoEntities db = new ComercioRoboticoEntities();

        // GET: Paises
        public ActionResult Index()
        {
            List<Paises> listado = db.Paises.Where(x => x.eliminado == false).ToList();
            return View(listado);
        }

        // GET: Paises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paises paises = db.Paises.Find(id);
            if (paises == null)
            {
                return HttpNotFound();
            }
            return View(paises);
        }

        // GET: Paises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Paises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Paises paises)
        {
            if (ModelState.IsValid)
            {
                db.Paises.Add(paises);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paises);
        }

        // GET: Paises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paises paises = db.Paises.Find(id);
            if (paises == null)
            {
                return HttpNotFound();
            }
            return View(paises);
        }

        // POST: Paises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Paises paises)
        {
            if (ModelState.IsValid)
            {
                Paises pai = db.Paises.Find(paises.id);
                pai.nombre = paises.nombre;
                pai.Regiones = paises.Regiones;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paises);
        }

        // GET: Paises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paises paises = db.Paises.Find(id);
            if (paises == null)
            {
                return HttpNotFound();
            }
            return View(paises);
        }

        // POST: Paises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paises paises = db.Paises.Find(id);
            if(paises != null)
            {
                paises.eliminado = true;
                paises.fechaEliminacion = DateTime.Now;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalesRoboticosG/AnimalesRoboticosG/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Conexiones.Animales.Models;

namespace AnimalesRoboticosG.Controllers
{
    public class PedidosController : Controller
    {
        private ComercioRoboticoEntities db = new ComercioRoboticoEntities();

        // GET: Pedidos
        public ActionResult Index()
        {
            List<Pedidos> listado = db.Pedidos.Where(x => x.eliminado == false).ToList();
            return View(listado);
        }

        // GET: Pedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // GET: Pedidos/Create
        public ActionResult Create()
        {
            ViewBag.direccion = new SelectList(db.Direcciones, "id", "nombre");
            ViewBag.idVenta = new SelectList(db.Ventas, "id", "descripcion");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedidos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.direccion = new SelectList(db.Direcciones, "id", "nombre", pedidos.direccion);
            ViewBag.idVenta = new SelectList(db.Ventas, "id", "descripcion", pedidos.idVenta);
            return View(pedidos);
        }

        // GET: Pedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            ViewBag.direccion = new SelectList(db.Direcciones, "id", "nombre", pedidos.direccion);
            ViewBag.idVenta = new SelectList(db.Ventas, "id", "descripcion", pedidos.idVenta);
            return View(pedidos);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                Pedidos ped = db.Pedidos.Find(pedidos.id);
                ped.idVenta = pedidos.idVenta;
                ped.fecha = pedidos.fecha;
                ped.fechaEnvio = pedidos.fechaEnvio;
                ped.nombreDestinatario = pedidos.nombreDestinatario;
                ped.direccion = pedidos.direccion;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.direccion = new SelectList(db.Direcciones, "id", "nombre", pedidos.direccion);
            ViewBag.idVenta = new SelectList(db.Ventas, "id", "descripcion", pedidos.idVenta);
            return View(pedidos);
        }

        // GET: Pedidos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedidos pedidos = db.Pedidos.Find(id);
            if(pedidos != null)
            {
                pedidos.eliminado = true;
                pedidos.fechaEliminacion = DateTime.Now;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalesRoboticosG/AnimalesRoboticosG/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Conexiones.Animales.Models;

namespace AnimalesRoboticosG.Controllers
{
    public class VentasController : Controller
    {
        private ComercioRoboticoEntities db = new ComercioRoboticoEntities();

        // GET: Ventas
        public ActionResult Index()
        {
            List<Ventas> listado = db.Ventas.Where(x => x.eliminado == false).ToList();
            return View(listado);
        }

        // GET: Ventas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            return View(ventas);
        }

        // GET: Ventas/Create
        public ActionResult Create()
        {
            ViewBag.idMetodoPago = new SelectList(db.MetodoPagos, "id", "formaPago");
            ViewBag.idUsuario = new SelectList(db.Usuarios, "id", "nombre");
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                db.Ventas.Add(ventas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idMetodoPago = new SelectList(db.MetodoPagos, "id", "formaPago", ventas.idMetodoPago);
            ViewBag.idUsuario = new SelectList(db.Usuarios, "id", "nombre", ventas.idUsuario);
            return View(ventas);
        }

        // GET: Ventas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            ViewBag.idMetodoPago = new SelectList(db.MetodoPagos, "id", "formaPago", ventas.idMetodoPago);
            ViewBag.idUsuario = new SelectList(db.Usuarios, "id", "nombre", ventas.idUsuario);
            return View(ventas);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                Ventas ven = db.Ventas.Find(ventas.id);
                ven.fecha = ventas.fecha;
                ven.total = ventas.total;
                ven.idUsuario = ventas.idUsuario;
                ven.descripcion = ventas.descripcion;
                ven.idMetodoPago = ventas.idMetodoPago;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idMetodoPago = new SelectList(db.MetodoPagos, "id", "formaPago", ventas.idMetodoPago);
            ViewBag.idUsuario = new SelectList(db.Usuarios, "id", "nombre", ventas.idUsuario);
            return View(ventas);
        }

        // GET: Ventas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventas ventas = db.Ventas.Find(id);
            if (ventas == null)
            {
                return HttpNotFound();
            }
            return View(ventas);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ventas ventas = db.Ventas.Find(id);
            if(ventas != null)
            {
                ventas.eliminado = true;
                ventas.fechaEliminacion = DateTime.Now;
                db.SaveChanges();
            }
       
          
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalesRoboticosG/AnimalesRoboticosG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Animales Roboticos</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href="@Url.Action("Index", "Home")"><img width="90" height="90" src="~/Content/imagenGeneral/LogoPet.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mercancia
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "Productos")">Productos</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "ImagenesProductos")">Imagenes de los Productos</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Categorias")">Categorías</a>
                        </div>

                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Finanzas
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "Ventas")">Ventas</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "DetalleVentas")">Detalle de Ventas</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Index", "MetodoPagos")">Metodos de pago</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ubicación
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "Comunas")">Comunas</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Regiones")">Regiones</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Paises")">Paises</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Index", "Direcciones")">Direcciones</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Solicitudes de Compra
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "Pedidos")">Pedidos</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "DetallePedidos")">Detalle de pedidos</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user"></i> Cuentas de usuarios
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "Usuarios")">Usuarios</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Index", "Perfiles")">Perfiles</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <br />
    <br />


    <section>
        @RenderBody()
    </section>
    <br />
    <br />

    <!-- Footer -->
    <footer class="page-footer font-small cyan darken-3">

        <!-- Footer Elements -->
        <div class="container">

            <!-- Redes Sociales -->
            <ul class="list-unstyled list-inline text-center">
                <li class="list-inline-item">
                    <i class="fa fa-linux" style="font-size: 32px;display:block;height:30px;color:purple"></i>
                </li>
                <li class="list-inline-item">
                    <i class="fa fa-github" style="font-size: 32px;display:block;height:30px;color:black"></i>
                </li>
                <li class="list-inline-item">
                    <i class="fa fa-phone" style="font-size: 32px;display:block;height:30px"></i>
                </li>
                <li class="list-inline-item">
                    <i class="fa fa-cloud" style="font-size: 32px;display:block;height:30px;color:lightskyblue"></i>
                </li>
            </ul>

        </div>
        <!-- Footer Elements -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright:
            AnimalesRoboticos.com
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>