AnimalesRoboticosG/AnimalesRoboticosG/Controllers/ImagenesProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Conexiones.Animales.Models;

namespace AnimalesRoboticosG.Controllers
{
    public class ImagenesProductosController : Controller
    {
        private ComercioRoboticoEntities db = new ComercioRoboticoEntities();

        // GET: ImagenesProductos
        public ActionResult Index()
        {
            var imagenesProductos = db.ImagenesProductos.Include(i => i.Productos);
            return View(imagenesProductos.ToList());
        }

        // GET: ImagenesProductos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImagenesProductos imagenesProductos = db.ImagenesProductos.Find(id);
            if (imagenesProductos == null)
            {
                return HttpNotFound();
            }
            return View(imagenesProductos);
        }

        // GET: ImagenesProductos/Create
        public ActionResult Create()
        {
            ViewBag.idProducto = new SelectList(db.Productos, "id", "nombre");
            return View();
        }

        // POST: ImagenesProductos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ImagenesProductos imagenesProductos, HttpPostedFileBase imagen)
        {
            string ruta = Server.MapPath("/Content/img");
            if (ModelState.IsValid)
            {
                if (imagen == null)
                {
                    ViewBag.idProducto = new SelectList(db.Productos, "id", "nombre");
                    ViewBag.Mensaje = "Debe subir una imágen";
                    return View("Create");
                }
                imagen.SaveAs($"{ruta}/{imagen.FileName}");
                imagenesProductos.url = $"/Content/img/{imagen.FileName}";
                db.ImagenesProductos.Add(imagenesProductos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idProducto = new SelectList(db.Productos, "id", "nombre", imagenesProductos.idProducto);
            return View(imagenesProductos);
        }

        // GET: ImagenesProductos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImagenesProductos imagenesProductos = db.ImagenesProductos.Find(id);
            if (imagenesProductos == null)
            {
                return HttpNotFound();
            }
            ViewBag.idProducto = new SelectList(db.Productos, "id", "nombre", imagenesProductos.idProducto);
            return View(imagenesProductos);
        }

        // POST: ImagenesProductos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ImagenesProductos imagenesProductos, HttpPostedFileBase imagen)
        {
            string ruta = Server.MapPath("/Content/img");
            if (ModelState.IsValid)
            {                   
                ImagenesProductos imagenesProductosDB = db.ImagenesProductos.Find(imagenesProductos.id);

                if (imagen != null)
                {
                    imagen.SaveAs($"{ruta}/{imagen.FileName}");
                    imagenesProductosDB.url = $"/Content/img/{imagen.FileName}";
                }
                imagenesProductosDB.idProducto = imagenesProductos.idProducto;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idProducto = new SelectList(db.Productos, "id", "nombre", imagenesProductos.idProducto);
            return View(imagenesProductos);
        }

        // GET: ImagenesProductos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImagenesProductos imagenesProductos = db.ImagenesProductos.Find(id);
            if (imagenesProductos == null)
            {
                return HttpNotFound();
            }
            return View(imagenesProductos);
        }

        // POST: ImagenesProductos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ImagenesProductos imagenesProductos = db.ImagenesProductos.Find(id);
            db.ImagenesProductos.Remove(imagenesProductos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalesRoboticosG/AnimalesRoboticosG/Views/ImagenesProductos/Create.cshtml
@model Conexiones.Animales.Models.ImagenesProductos

@{
    ViewBag.Title = "Cargar Imagenes";
}

    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <i class="fa fa-plus-circle"></i><div class="card-header text-white bg-dark mb-3">Agregar Imágen</div>
                    <div class="card-body">
                        <form method="post" action="/ImagenesProductos/Create" enctype="multipart/form-data">
                            @Html.AntiForgeryToken()

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right">Producto</label>
                                <div class="col-md-6">
                                    @Html.DropDownList("idProducto", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.idProducto, "", new { @class = "text-danger" })
                                </div>
                                <label class="col-md-4 col-form-label text-md-right">Imágen</label>
                                <div class="col-md-6">
                                    <input type="file" name="imagen" />
                                </div>
                                </div>

                                <div class="col-md-6 offset-md-4">
                                    <input type="submit" value="Guardar" class="btn btn-success" />
                                </div>

</form>
                        </div>
                        @*@using (Html.BeginForm(new { enctype="multipart/form-data"}))*@
                        <div>
                            @Html.ActionLink("Volver", "Index")
                        </div>
                    </div>
                </div>
            </div>
        </div>
@ViewBag.Mensaje
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AnimalesRoboticosG/AnimalesRoboticosG/Views/ImagenesProductos/Delete.cshtml
@model Conexiones.Animales.Models.ImagenesProductos

@{
    ViewBag.Title = "Eliminar Imagen";
}

    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <i class="fa fa-remove"></i><div class="card-header text-white bg-dark mb-3">Eliminar Imágen</div>
                    <div class="form-group row">


                        <div class="col-md-6">
                            <label class="col-md-4 col-form-label text-md-right">Producto:</label>
                            @Html.DisplayFor(model => model.Productos.nombre)
                        </div>
                        </div>
                        <div class="col-md-6 offset-md-4">
                            <label class="justify-content-center">¿Está seguro que desea eliminar la imágen?</label>
                        </div>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="col-md-6 offset-md-4">
                                <input type="submit" value="Eliminar" class="btn btn-danger" /> |
                                @Html.ActionLink("Volver", "Index")
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

AnimalesRoboticosG/AnimalesRoboticosG/Views/ImagenesProductos/Details.cshtml
@model Conexiones.Animales.Models.ImagenesProductos

@{
    ViewBag.Title = "Detalles";
}

<div class="cotainer">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-black-50 bg-light">Detalle de la imágen</div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <strong>Producto:</strong>
                        @Html.DisplayFor(model => model.Productos.nombre)
                    </div>
                </div>
                @*@{
                    foreach (var img in Model.ImagenesProductos)
                    {
                        <img width="300" src="@img.url" />
                    }
                }*@

                <div class="col-md-6 offset-md-4">
                    <button type="button" class="btn btn-warning btn-sm">
                        <i class="fa fa-edit"></i>
                        @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
                    </button>
                </div>

                @Html.ActionLink("Volver", "Index")
            </div>
        </div>
    </div>
</div>

AnimalesRoboticosG/AnimalesRoboticosG/Views/ImagenesProductos/Edit.cshtml
@model Conexiones.Animales.Models.ImagenesProductos

@{
    ViewBag.Title = "Editar";
}

<div class="cotainer">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <i class="fa fa-edit"></i><div class="card-header text-white bg-dark mb-3">Modificar la imágen del producto</div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "ImagenesProductos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Producto</label>
                            <div class="col-md-6">
                                @Html.DropDownList("idProducto", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.idProducto, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Imágen</label>
                            <div class="col-md-6">
                                <input type="file" name="imagen" />
                            </div>
                            <img width="100" height="100" href="@Model.url" />
                        </div>

                        <div class="col-md-6 offset-md-4">
                            <input type="submit" value="Guardar" class="btn btn-warning" />
                        </div>
                    }
                </div>
                <div>
                    @Html.ActionLink("Volver", "Index")
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AnimalesRoboticosG/AnimalesRoboticosG/Views/ImagenesProductos/Index.cshtml
@model IEnumerable<Conexiones.Animales.Models.ImagenesProductos>

@{
    ViewBag.Title = "Imagenes";
}


    <div class="d-flex ml-5 mr-5">

        <table class="table">
            <thead class="thead-dark table-bordered">
                <tr>
                    <th>
                        <label>Imágen</label>
                    </th>
                    <th>
                        <label>Producto</label>
                    </th>
                    <th>
                        <label>Opciones</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th>
                            <img width="100" src="@item.url" />
                        </th>
                        <td>
                            @Html.DisplayFor(modelItem => item.Productos.nombre)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                            @Html.ActionLink("Ver", "Details", new { id = item.id }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.id })
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot class="thead-dark table-bordered">
                <tr>
                    <th>
                        <label>Imágen</label>
                    </th>
                    <th>
                        <label>Producto</label>
                    </th>
                    <th>
                        <label>Opciones</label>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
<div class="d-flex justify-content-end mr-5"><a href="@Url.Action("Create")" class="btn btn-success"><i class="fa fa-plus-circle"></i> Agregar</a></div>